spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: CHALLENGESDB
    password: SUGUNA
    driver-class-name: oracle.jdbc.driver.OracleDriver 
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
      
entitymanager:
 packagesToScan: com.myapp.rentcloud.model
 



